### ISSUE TITLE
yolov5x_fp32_batch_1.engine 是什么文件？如何生成？

### ISSUE THREAD

**Issue by zsffuture** [ttanzhiqiang/onnx_tensorrt_project#1]
您好，感谢您的开源工作，如题我现在已经转换得到onnx了，但是另一个文件yolov5x_fp32_batch_1.engine不知道怎么生成或者得到的，新手，希望大神能指导一下，谢谢

**Comment by ttanzhiqiang** [comment]
通过代码yolov5_detector.cpp将onnx生成engine文件，就可以做trt推理了

**Comment by abhigoku10** [comment]
@ttanzhiqiang  do you have python code to generate engine file and inference the engine file ??

**Comment by ttanzhiqiang** [comment]
no ,this is c++ project,you can look it ,and you write python code to generate engine file and inference the engine file
