### ISSUE TITLE
Unet推理速度和占用显存问题

### ISSUE THREAD

**Issue by Tristesse-stk** [ttanzhiqiang/onnx_tensorrt_project#11]
如题，我按照您的配置成功运行起来了unet.cpp，图像指定大小是512*512，显卡型号3060，mode是2（INT8）但是检测下来检测速度是在77ms左右，与您在此项目中的Benchmark中提到的16ms相差甚远，显存占用也有1.2G，请问根据您的经验来看我还有哪些地方没设置对？
![Snipaste_2021-09-18_13-49-24](https://user-images.githubusercontent.com/55178320/133877796-77d67524-395b-401f-92a8-33f633ed0d27.png)

**Comment by ttanzhiqiang** [comment]
我是用2080ti显卡跑的，你可以尝试一下其他算法，比如yolov5这个，看看差多少。

**Comment by Tristesse-stk** [comment]
我试了下yolov5，在mode0(FP32)和mode2(INT8)下都是75ms左右，在mode1(FP16)下一直生成不了engine文件。
![Yolov5xINT8结果图](https://user-images.githubusercontent.com/55178320/133958882-1b9f4683-80b0-4446-97ec-37054ef87e6f.png)
![Yolov5xFP32结果图](https://user-images.githubusercontent.com/55178320/133958896-1fa39211-5bda-4de0-a9ea-fbdbf97a612a.png)
我的main()设置如下，其他没改。请问是不是我还有哪里没设置正确？
![yolov5main函数设置](https://user-images.githubusercontent.com/55178320/133958977-4468ac7a-fe45-4259-80f7-4c3466eb2597.png)

**Comment by ttanzhiqiang** [comment]
你看看3060支持FP16不，配置应该没问题的

**Comment by Tristesse-stk** [comment]
您好，问题已解决，是因为我没把Debug模式切到Release模式下，切过去后推理速度和显存占用就合理了。
