### ISSUE TITLE
centernet fps?

### ISSUE THREAD

**Issue by codylcs** [ttanzhiqiang/onnx_tensorrt_project#2]
great work! how fast of centernet tensorrt model?

**Comment by ttanzhiqiang** [comment]
thanks for you problem. I test my project ，centernet tensort only 78ms，I think it is wrong,I will repair it

**Comment by ttanzhiqiang** [comment]
![image](https://user-images.githubusercontent.com/38750855/126745278-07996215-3fe8-42b6-9463-951bd3be32a2.png)

now,centernet tensorrt  15.7ms in inference and 36.49ms in detect
