### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by xinsuinizhuan** [ttanzhiqiang/onnx_tensorrt_project#5]
my windows eviroment is:
cuda 11.0 
vs2019
how to run?
when i run, it tip me:
can not find the nvrtc64_111_0.dll

which third_model  should i to recompile them?

**Comment by ttanzhiqiang** [comment]
you should use cuda11.1

**Comment by xinsuinizhuan** [comment]
> 
> 
> you should use cuda11.1

If i use the cuda11.0, which 3rdparty should i recompile?

**Comment by ttanzhiqiang** [comment]
you should change tensorrt for cuda11.0

**Comment by xinsuinizhuan** [comment]
OK.thank you. It works, now .but where i run the tiny_tensorrt_dyn_onnx, it have no:
model\yolov5\yolov5-v5_weight\yolov5m.onnx

**Comment by xinsuinizhuan** [comment]
Others, I want to run yolor, yolox and other items，how i switch to run them?

**Comment by ttanzhiqiang** [comment]
look https://share.weiyun.com/CJCwngAM.
and  tiny_tensorrt_dyn_onnx  is dynamic shape,you should use tiny_tensorrt_onnx.sln

**Comment by xinsuinizhuan** [comment]
> tiny_tensorrt_onnx.sln

yes, i run it, but now the have no model of the yolov5, could you share them?
look, have no model of yolov5
![图片](https://user-images.githubusercontent.com/40679769/126943666-f851d1af-8ac5-4ec8-8bad-a53f57cf769b.png)
