### ISSUE TITLE
KeyError: 'down_stride'

### ISSUE THREAD

**Issue by MeiXiao09** [ttanzhiqiang/onnx_tensorrt_project#8]
![image](https://user-images.githubusercontent.com/32815600/127653492-8b783ecf-c842-4be0-833c-014971aa86e5.png)

**Comment by ogoun** [comment]
The same error, i try convert Yolov4 and Yolov4-p5 darknet models. And got error:
```
File "yolo_to_onnx.py", line 750, in <module>
    main()
  File "yolo_to_onnx.py", line 742, in main
    model_def = builder.build_onnx_graph(
  File "yolo_to_onnx.py", line 324, in build_onnx_graph
    major_node_specs = self._make_onnx_node(layer_name, layer_dict)
  File "yolo_to_onnx.py", line 397, in _make_onnx_node
    node_creators[layer_type](layer_name, layer_dict)
  File "yolo_to_onnx.py", line 700, in _make_yolo_node
    down_stride = int(layer_dict['down_stride'])
KeyError: 'down_stride'
```

**Comment by ttanzhiqiang** [comment]
you can look my yolov3.cfg.
like https://github.com/ttanzhiqiang/onnx_tensorrt_project/blob/main/model/darknet_onnx_tensorrt_yolo/yolov3.cfg
![image](https://user-images.githubusercontent.com/38750855/127802135-99a7da7f-7d0e-4553-850c-39104b847403.png)

you add down_stride = 8 in yolo Plugin.

**Comment by MeiXiao09** [comment]
@ttanzhiqiang  ok, i try to use your yolov3.cfg, it works!
